### ISSUE TITLE
collect / compile data sources

### ISSUE THREAD

**Issue by Linn2202** [ouzibigouzi/Hydroponics#11]
Focus on hydroponic plants:
- salads
- strawberries
- ...
[ ] Test

[ ] Aufgabe 2

Provide links of source and short overview of content (species, disease, nutrition, size/amount of data, type of image)

**Comment by LnawI** [comment]
On 27th June, afternoon, we will discuss data sources and decide which one we will use.

**Comment by LnawI** [comment]
[] Test
[] Aufgabe 2
